import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Foreign Exchange Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className=''>
        <h1 class="title">Foreign Exchange Calculator</h1>
        <section>
          GBP: <input />
        </section>
        <section>
        <h2>Converted</h2>
        <ul>
          <li>
            <p><strong>EUROS:</strong>1.20</p>
          </li>
          <li>
            <a href="/new" class="button">Add new currency</a>
          </li>
        </ul>
        </section>
        </div>
      </main>
    </>
  )
}
